### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by ndunand** [UOC/Tandem#6]
Hello,

We successfully managed to install the LTI provider and configure Moodle as the LTI consumer, but we lack information as to how to create exercises. It seems that exercises need to be uploaded by the teacher in the form of a ZIP file, containing some XML file.

Could you shed some light on this?

TIA,
Nicolas

**Comment by abertranb** [comment]
Hello to upload exercises you can download it from http://oer.speakapps.org/xwiki/bin/view/Main/

Follow the instructions from:
*Tandem*
http://langblog.speakapps.org/speakappsinfo/category/teacher/tandem-teacher/how-to-use-tandem-tandem-teacher/
*OER*
http://langblog.speakapps.org/speakappsinfo/category/teacher/oer/introduction/?f=OER
*Upload Tandem Activities*
http://langblog.speakapps.org/speakappsinfo/category/teacher/oer/uploading-tandem-activities-to-tandem-tool/?f=OER.

Bests regards

**Comment by ndunand** [comment]
Thanks a lot!

**Comment by ndunand** [comment]
@abertranb another question (please redirect me if there is a more appropriate place to ask questions):

How can one create Tandem activities? I tried to register on OER, but I can't seem to be able to create new activities. Is there any other way?

**Comment by abertranb** [comment]
Hello @ndunand you have to register to Speakapps (http://moodle.speakapps.org/) and then you will be able to create it

Sorry for the delay
