### ISSUE TITLE
[Suggestion] Add autoload

### ISSUE THREAD

**Issue by Raggaer** [UOC/Tandem#7]
Looking through the code I see a lot of require calls. What about making use of PHP class autoload?

[http://php.net/manual/es/language.oop5.autoload.php](http://php.net/manual/es/language.oop5.autoload.php)

There is also the posiblity of dividing the whole project into modules and using [Composer](https://getcomposer.org/) to include them

**Comment by abertranb** [comment]
Thanks @Raggaer will be update it in next versions
